name: Update Go Pkg Version

on:
  push:
    tags:
      - 'v*'  # Trigger only when a new version tag is pushed
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  update_go_pkg_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version from tag
      id: extract_version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo "VERSION=${TAG}" >> $GITHUB_ENV

    - name: Update go pkg cache
      run: |
        curl -v https://sum.golang.org/lookup/github.com/${GITHUB_REPOSITORY}@${{ env.VERSION }}
      env:
        VERSION: ${{ env.VERSION }}
